/*
 * This source file was generated by the Gradle 'init' task
 */
package org.starlitnova;

import javax.swing.*;
import java.awt.*;

public class App {
    private Renderer renderer;

    public App() {
        JFrame frame = new JFrame("Shroom");
        renderer = new Renderer();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(renderer);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        App app = new App();
    }
}
